language: php
dist: trusty

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

notifications:
  on_success: never
  on_failure: always

git:
  depth: 1

install:
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - composer check-code
  - composer test
